from typing import Optional, Protocol, runtime_checkable

from src.application.dto.site import SiteDto, SiteKeywordDto, SiteSubdomainDto


@runtime_checkable
class SiteDao(Protocol):
    async def create_site(self, site: SiteDto) -> SiteDto: ...

    async def get_site_by_id(self, site_id: int) -> Optional[SiteDto]: ...

    async def get_site_by_base_domain(self, base_domain: str) -> Optional[SiteDto]: ...

    async def get_all_sites(self) -> list[SiteDto]: ...

    async def update_site(self, site: SiteDto) -> Optional[SiteDto]: ...

    async def create_subdomain(self, subdomain: SiteSubdomainDto) -> SiteSubdomainDto: ...

    async def get_subdomain_by_id(self, subdomain_id: int) -> Optional[SiteSubdomainDto]: ...

    async def get_subdomain_by_host(self, host: str) -> Optional[SiteSubdomainDto]: ...

    async def get_subdomains_by_site_id(self, site_id: int) -> list[SiteSubdomainDto]: ...

    async def update_subdomain(self, subdomain: SiteSubdomainDto) -> Optional[SiteSubdomainDto]: ...

    async def create_keyword(self, keyword: SiteKeywordDto) -> SiteKeywordDto: ...

    async def get_keyword_by_id(self, keyword_id: int) -> Optional[SiteKeywordDto]: ...

    async def get_keywords_by_subdomain_id(self, subdomain_id: int) -> list[SiteKeywordDto]: ...

    async def update_keyword(self, keyword: SiteKeywordDto) -> Optional[SiteKeywordDto]: ...

    async def delete_keyword(self, keyword_id: int) -> bool: ...
